/* eslint-disable @typescript-eslint/no-explicit-any */
// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`
// empty interface intentionally allowed for generated environment typing
declare interface CloudflareEnv { [key: string]: any }
